/**
 * Created by 9i
 * @Date 2017/12/4
 */
export startBgUrl from './images/startBg.jpg'
export startBgLgUrl from './images/startBg_Lg.jpg'
export startButtonUrl from './images/startButton.png'
export planeImg from './images/player.png'
export bgImg1 from './images/bg_01.jpg'
export bgImg2 from './images/bg_02.jpg'
export bgImg3 from './images/bg_03.jpg'
export bgImg4 from './images/bg_04.jpg'
export bgImg5 from './images/bg_05.jpg'
export hpImg from './images/img_HP.png'
export numImg0 from './images/0.png'
export numImg1 from './images/1.png'
export numImg2 from './images/2.png'
export numImg3 from './images/3.png'
export numImg4 from './images/4.png'
export numImg5 from './images/5.png'
export numImg6 from './images/6.png'
export numImg7 from './images/7.png'
export numImg8 from './images/8.png'
export numImg9 from './images/9.png'
export bulletBuff from './images/bullet.png'
export bullet from './images/bullet1.png'
export enemy1 from './images/enemy.png'
export enemy2 from './images/enemy1.png'
export enemy3 from './images/bigEmeny.png'
export enemy4 from './images/dj1.png'
export enemy5 from './images/dj6.png'
export boss1 from './images/dj1.png'
